import Navigation from "@/components/ui/navigation";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <div className="border border-black border-solid">
        <Navigation />
      </div>
      <main>{children}</main>
    </>
  );
}
